runtime: nodejs
env: flex
env_variables:
  NODE_ENV: "prod"
  LOG_LEVEL: "info"
  DB_HOST: "ds337718.mlab.com"
  DB_PORT: "37718"
  DB_DATABASE: "mosohaya"
  DB_USERNAME: "thitapp"
  DB_PASSWORD: "thitapp080"
